spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/employeeDb
    username: 'root'
    password: '123456'
  sql:
    init:
      mode: always
      platform: h2

jwt:
  secret: "employee_management_system"